Repository wkentaro/gdown, pull requests merged in 2022-02, with the labels that each got.

#147 Mitigate permission denied error with &confirm=t
  gdown/download.py
Labels: enhancement

#150 Add how to upgrade Gdown to the README.md
  README.md
Labels: enhancement

#152 Update the URL for folder download in the README
  README.md
Labels: enhancement

#154 Use tempfile.mktemp for Windows
  gdown/download.py
Labels: bug

#155 Update `use_cookies` arg in `download_folder` README example.
  README.md
Labels: documentation

#158 Update README.md
  README.md
Labels: documentation

#160 Allow users to specify a file ID without `--id`
  .github/workflows/ci.yml
  README.md
  gdown/cli.py
Labels: enhancement
