Repository wkentaro/gdown, pull requests merged in 2024-02, with the labels that each got.

#317 Add dry_run option to download_folder to return the list of files without download
  gdown/download_folder.py
  tests/test_download_folder.py
Labels: feature

#318 Add FAQ link to error messages
  gdown/download.py
  gdown/download_folder.py
Labels: enhancement

#323 Fix typos in README.md
  README.md
Labels: other

#321 BUG: Download folder with "skip_download=True" creates an output folder
  gdown/download_folder.py
Labels: fix

#324 Run GitHub Actions on macOS, Ubuntu, and Windows
  .github/workflows/ci.yml
Labels: other
