Repository wkentaro/gdown, pull requests merged in 2024-05, with the labels that each got.

#361 Show resume progress bar from the middle
  gdown/download.py
Labels: enhancement

#343 Typo in arg help text
  gdown/__main__.py
Labels: other

#351 Feature: preserve GDrive's last modified time when downloading
  gdown/download.py
Labels: feature
